name: qrcode_scanner
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  qr_flutter: ^4.1.0
  simple_barcode_scanner: ^0.1.1
  url_launcher: ^6.3.0
  share_plus: ^10.0.0
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images.jpg"
  min_sdk_android: 21

flutter:
  uses-material-design: true
